// DOM integration check, not a rendered-browser or physical-device test.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require('linkedom'),{indexedDB}=require('fake-indexeddb');
const {webcrypto}=require('node:crypto');
const storage=new Map(),errors=[],blobs=[];class CaptureURL extends URL{static createObjectURL(b){blobs.push(b);return 'blob:capture'}static revokeObjectURL(){}}
const tick=()=>new Promise(r=>setTimeout(r,10));
function app(updater){const {window}=parseHTML(fs.readFileSync('dist/index.html','utf8'));if(updater)window.MeridianUpdater=updater;else delete window.MeridianUpdater;const doc=window.document;Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){const opts=Array.from(this.querySelectorAll('option'));return (opts.find(o=>o.hasAttribute('selected'))||opts[0])?.getAttribute('value')??(opts[0]?.textContent||'');},set(value){for(const o of this.querySelectorAll('option')){if((o.getAttribute('value')??o.textContent)===value)o.setAttribute('selected','');else o.removeAttribute('selected');}}});doc.querySelector('dialog').showModal=function(){this.open=true};doc.querySelector('dialog').close=function(){this.open=false};const location={href:'https://meridian.test/',hash:'',protocol:'https:'};window.scrollTo=()=>{};window.indexedDB=indexedDB;
const sandbox={window,document:doc,location,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},indexedDB,crypto:webcrypto,console:{...console,error:(...args)=>errors.push(args.map(String).join(' '))},navigator:{},Intl,Date,URL:CaptureURL,TextEncoder,TextDecoder,Blob,File:global.File,Uint8Array,ArrayBuffer,setTimeout,clearTimeout,setInterval:()=>0,btoa,atob,fetch:async()=>{throw Error('No network during DOM checks')}};vm.createContext(sandbox);for(const file of ['data.js','core.js','app.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),sandbox,{filename:file});return{window,doc,click:async(selector)=>{const el=doc.querySelector(selector);assert.ok(el,'Missing '+selector);el.dispatchEvent(new window.Event('click',{bubbles:true}));await tick()},read:()=>JSON.parse(storage.get('meridian-v1'))};}
(async()=>{let a=app();assert.match(a.doc.body.textContent,/Seu futuro começa/);
for(const r of ['exams','calendar','plan','focus','review','practice','errors','materials','documents','writing','insights','handoff','settings']){await a.click('[data-action="nav"][data-route="'+r+'"]');assert.ok(a.doc.querySelector('h1'),r+' did not render');}
await a.click('[data-action="nav"][data-route="review"]');await a.click('[data-action="reveal"]');await a.click('[data-action="grade"][data-grade="0"]');assert.equal(a.read().cards[0].reviews,1);
await a.click('[data-action="new-card"]');a.doc.querySelector('#card-front').value='Teste de retenção';a.doc.querySelector('#card-back').value='Resposta de teste';await a.click('[data-action="save-card"]');assert.ok(a.read().cards.some(c=>c.front==='Teste de retenção'));
await a.click('[data-action="nav"][data-route="plan"]');await a.click('[data-action="generate-plan"]');assert.ok(a.read().plan.length);
await a.click('[data-action="nav"][data-route="focus"]');await a.click('[data-action="log-session"]');a.doc.querySelector('#s-note').value='Aprendi a testar sem consultar.';await a.click('[data-action="save-session"]');assert.equal(a.read().sessions.length,1);
await a.click('[data-action="nav"][data-route="practice"]');await a.click('[data-action="quiz-start"]');await a.click('[data-action="quiz-select"][data-answer="0"]');await a.click('[data-action="quiz-answer"]');assert.equal(a.read().answers.length,1);
await a.click('[data-action="nav"][data-route="calendar"]');await a.click('[data-action="new-event"]');a.doc.querySelector('#event-title').value='Revisão pessoal';await a.click('[data-action="save-event"]');assert.equal(a.read().events.length,1);
await a.click('[data-action="nav"][data-route="writing"]');const draft=a.doc.querySelector('#essay-text');draft.value='Meu rascunho deve sobreviver a uma troca de tela.';draft.dispatchEvent(new a.window.Event('input',{bubbles:true}));await a.click('[data-action="nav"][data-route="home"]');assert.equal(a.read().essays[0].text,draft.value);
await a.click('[data-action="nav"][data-route="handoff"]');await a.click('[data-action="export-sync"]');
const pack=JSON.parse(await blobs.at(-1).text());assert.equal(pack.format,'meridian-sync');assert.ok(pack.targets.length>0);assert.equal(pack.performance.reduce((n,r)=>n+r.total,0),1);assert.ok(pack.performance[0].name&&pack.performance[0].name!==undefined);assert.ok(pack.upcoming.some(e=>e.title==='Revisão pessoal'||e.start));
const before=a.read();a=app();const after=a.read();assert.equal(after.cards.length,before.cards.length);assert.equal(after.sessions.length,1);assert.equal(after.events.length,1);assert.ok(a.doc.body.textContent.includes('25'));
{const calls=[];let u;u=app({appInfo:()=>JSON.stringify({versionCode:3,versionName:'1.0.3'}),checkUpdate(){calls.push('check');u.window.meridianUpdate({type:'check',available:true,versionCode:5,versionName:'1.0.5'});},installUpdate(){calls.push('install');u.window.meridianUpdate({type:'progress',pct:50});u.window.meridianUpdate({type:'installing'});}});
await u.click('[data-action="nav"][data-route="settings"]');assert.match(u.doc.body.textContent,/Instalado: versão 1\.0\.3 · build 3/);
await u.click('[data-action="check-update"]');assert.match(u.doc.body.textContent,/Nova versão 1\.0\.5 disponível/);
await u.click('[data-action="nav"][data-route="home"]');assert.ok(u.doc.querySelector('.update-banner'),'home shows the update banner');
await u.click('[data-action="install-update"]');assert.ok(calls.includes('install'));assert.match(u.doc.body.textContent,/Confirme a instalação/);
const plain=app();await plain.click('[data-action="nav"][data-route="settings"]');assert.ok(!/Verificar atualização/.test(plain.doc.body.textContent),'no updater card outside the APK');}
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: 14 screens, sync pack, in-app update flow, card review/addition, plan, session, question, event, writing autosave, persisted reload. No DOM runtime exceptions.');})().catch(e=>{console.error(e);process.exitCode=1});
